### ISSUE TITLE
Constraint on sqlalchemy seems to prevent installing Parsl with python>=3.8

### ISSUE THREAD

**Issue by xylar** [conda-forge/parsl-feedstock#4]
The constraint to `sqlalchemy ==1.3.3`:
https://github.com/conda-forge/parsl-feedstock/blob/master/recipe/meta.yaml#L36
seems to prevent installation of `parsl` with `python >=3.8`.  
If I do:
```
$ conda search --info sqlalchemy=1.3.3
```
I see support only for python 2.7, 3.6 and 3.7.

It seems like this constraint isn't needed, based on the upstream requirements (`sqlalchemy>=1.3.0,!=1.3.4`):
https://github.com/Parsl/parsl/blob/1.0.0/setup.py#L11

If you are open to it, I would like to make a PR for a new build with the same constraints on `sqlalchemy` as upstream.  I wanted to make sure this was okay before making the PR.

**Comment by yadudoc** [comment]
This should be fine. @xylar, Thanks for reporting this, and I would appreciate a PR if it's not too much trouble.

**Comment by xylar** [comment]
Okay, it's no problem.
